//try-catch  exception handling
console.log('start execution');
exp = "10/2/**"
try {
    
result = eval(exp)   //eval method is a predefined methods of evaluation
console.log(result);

} catch (error) {
    console.log('expression is wrong');
    
}
num1 =10
num2 =20
sum = num1+num2
console.log(sum);

console.log('execution end');